sim/verilator/conda-inttypes.patch, sim/verilator/meta.yaml, sim/verilator/run_test.sh
In order for Verilator to support FST tracing with Conda, the package needs to call out 'zlib' as a dependency, and the tracing file needs to define __STD_FORMAT_MACROS. This patch adds these changes, and ensures they are tested by the build tests.
Signed-off-by: Matthew Ballance <matt.ballance@gmail.com>
=> Enable verilator build to support FST tracing

.travis.yml, README.md, formal/symbiyosys/build.sh, formal/symbiyosys/fixup_lingeling.patch, formal/symbiyosys/meta.yaml, formal/symbiyosys/run_test.sh, formal/symbiyosys/test/demo3.sby
This PR adds support for building Symbiyosys on Linux platforms. 
I'm aware of one open issue that I could use some advice with: obtaining a version. I used the Verilator meta.yaml file as a basis for the Symbiyosys one, but the Verilator version mechanism doesn't work well for Symbiyosys. Any advice on typical approaches?
=> Add Conda build/test files for Symbiyosys and Boolector/Z3 solvers

.travis.yml
Upstream changes prevent it from compilation on macOS.
=> Allow VTR on macOS to fail

conda_build_config.yaml
`conda-build` v20.1+ doesn't have any default value defined for `CONDA_BUILD_SYSROOT` anymore and the `conda_build_config.yaml` from `.travis` is ignored by `conda-build`.
=> Fix macOS compiling problems

.travis.yml, syn/symbiflow-yosys/build.sh, syn/symbiflow-yosys/makefile-conda-config.patch, syn/symbiflow-yosys/meta.yaml, syn/symbiflow-yosys/tests-use-vvp.patch
On Linux it's basically the same recipe as in the `SymbiFlow/conda-packages` repository.
Stage is "Has first level dependencies" because recipe requires `iverilog` package.
=> Add `symbiflow-yosys` for Linux and macOS

.travis.yml, bit/prjxray-db/build.sh, bit/prjxray-db/meta.yaml, bit/prjxray-tools/build.sh, bit/prjxray-tools/condarc, bit/prjxray-tools/meta.yaml
This recipe is based on 'Symbiflow/conda-packages' one.
fpga-tool-perf depends on prjxray-db
symbiflow-examples depends on both prjxray-db and prjxray-tools
=> Add prjxray-db & prjxray-tools package

.travis.yml, syn/quicklogic-yosys-plugins/build.sh, syn/quicklogic-yosys-plugins/meta.yaml
This is almost the same recipe as can be currently found in the `QuickLogic-Corp/ql_conda_eda` repository.
The only changes are:
* name of the package,
* `quicklogic-yosys` requirement instead of `yosys`,
* removing `condarc` (ie. `ql_conda_eda` channel won't be used),
* `make` as a requirement because Travis' `make` fails macOS builds.
=> Add quicklogic-yosys-plugins recipe for Linux and macOS

.travis.yml, pnr/arachne/meta.yaml, pnr/nextpnr/ecp5/meta.yaml, pnr/nextpnr/generic/meta.yaml, pnr/nextpnr/ice40/meta.yaml
The stage of some packages has changed because `symbiflow-yosys` is
built at the "Has first level dependencies" stage.
Comments were added with required packages built in this repository to
make the stage selection easier in case of any further changes.
`nextpnr-*` packages on Windows are allowed to fail because currently
`symbiflow-yosys` isn't built for Windows.
`symbiyosys` has a misleading name – it needs to be built with upstream `yosys`.
=> Set proper `yosys` in packages requiring it

.travis.yml, pnr/quicklogic-vtr-gui/condarc, pnr/quicklogic-vtr-gui/meta.yaml, pnr/quicklogic-vtr/meta.yaml
Installing built `quicklogic-vtr` metapackage will result in installing
`vtr` package in the exact same version and build as the metapackage.
Metapackages built in CI can be tested using:
```
conda install -c litex-hub/label/travis-quicklogic-vtr-201232771 quicklogic-vtr
conda install -c conda-forge -c litex-hub/label/travis-quicklogic-vtr-201232771 quicklogic-vtr-gui
```
=> Add `quicklogic-*` metarecipes for `vtr`/`vtr-gui`

pnr/arachne/build.sh, pnr/arachne/meta.yaml, sim/verilator/meta.yaml, sim/verilator/run_test.sh
Using `resolved_packages` in run requirements results in adding exact
builds of the packages used during building as dependencies.
It often leads to dependency conflicts so it's better to have them
copied.
Other changes are because:
* verilator needs some C++ compiler during testing but it's not
necessary for running the verilator itself,
* arachne-pnr had icebox path dependent on gcc path which restricted
more reasonable separation of build/host packages.
=> Stop using `resolved_packages`

bit/prjxray-tools/condarc
The presence of condarc, specifically the conda-forge channel was forcing the libgcc-ng package to be >= 9.3.0 generating conflicts with other packages that require a previous version of the libgcc-ng package.
In general though, we do not want to make use of conda-forge, unless strictly required
=> bit: prjxray-tools: remove not needed condarc

pnr/nextpnr/ice40/meta.yaml
The boost packages v1.73 conflict with the clang 4.0 on macOS. It seems
it requires newer version of the compiler.
However, packages such as libraries linked should be placed in a `host`
environment. Also, there's rarely a need to have the same package as
both the `build` and the `host` requirement.
Therefore, to solve conflicts, the packages mentioned in both have been
removed from the `build` environment.
=> nextpnr-ice40: Fix building on macOS

syn/yosys/makefile-conda-config.patch
This is because some strings that get binary patched by the conda
installer might overlap with some internal strings used by yosys.
Without disabling merge-constants, the yosys share search path was
changing from "<binary path>/../share/yosys/" to "<binary path>/../share/" as
a result from conda stirng patching.
See https://github.com/SymbiFlow/conda-packages/pull/119
=> Don't merge constants for yosys for the yosys conda package.

pnr/vtr-gui/build.sh
The capnp-schema-dir is essential in tool-perf to get the path of the `capnp` schemas. Given the recent transition towards using upstream tools packages, this script was absent.
=> vtr: add capnp-schema-dir script to get its path

pnr/vtr-optimized/condarc
Such change will make `conda-build` get all required packages from the
`defaults` channel if they only exist there. Only the packages that
aren't available in that channel will be taken from the `conda-forge`
channel (`python-constraint`).
=> vtr-optimized: Give highest priority to the `defaults` channel

.github/workflows/build-packages.yml, sv-front/surelog-uhdm/condarc, sv-front/surelog-uhdm/meta.yaml, syn/yosys-uhdm/condarc, syn/yosys-uhdm/meta.yaml
This PR introduces additional `uhdm-integration` packages with python 3.8 dependency. This is required in SystemVerilog testing workflow (encountering the same problems as in https://github.com/litex-hub/litex-conda-eda/pull/68)
=> Build uhdm-integration packages for python 3.7 and 3.8

.github/workflows/build-packages.yml, syn/yosys-uhdm/build.sh, syn/yosys-uhdm/meta.yaml, syn/yosys-uhdm/yosys.patch
This PR fixes encouraged problems with ``uhdm-yosys`` package in ``fpga-tool-perf`` :
- includes whole yosys install in package (not only binary yosys file)
- uses conda compiler to compile yosys (and sets gcc/gxx aliases to conda compiler, as ``abc`` is using them directly, this fixes the problem with wrong path to yosys - share directory after compilation)
- uses ``PROGRAM_PREFIX`` to add prefix to the output files - this way we won't conflict with other yosys installed in the system, but it changes binary name to ``uhdm-yosys`` from ``yosys-uhdm`` (this means we need to adapt all repositories that is already using this package after merge.).
=> Fixes for uhdm-yosys package

sim/verilator/meta.yaml
I have added the following required runtime dependiencies to Verilator: cxx, bison, flex and ncurses
=> Fix runtime dependencies for Verilator

sim/verilator-uhdm/build.sh
Simulation test cases for verilator-uhdm in sv-tests are failing because of lacking verilator build results other than binaries as for e.g. `verilated.mk` file while using the verilator-uhdm conda package. This PR is fixing the package by including whole `image` directory contents just like in yosys-uhdm recipe: https://github.com/hdl/conda-eda/blob/master/syn/yosys-uhdm/build.sh#L20
Here is an example with mentioned failure: https://symbiflow.github.io/sv-tests-results/#UhdmVerilator|11.4.3|simple_plus_operator_sim
Error:
```
Vtop.mk:53: /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/verilator-uhdm_1614698043301/work/image/share/verilator/include/verilated.mk: No such file or directory
```
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
=> verilator-uhdm: build package with whole 'image' directory contents

.github/workflows/build-packages.yml, pnr/quicklogic-vtr-gui/meta.yaml, pnr/quicklogic-vtr/meta.yaml, sim/uhdm-integration-verilator/condarc, sim/uhdm-integration-verilator/meta.yaml, sim/uhdm-integration-yosys/condarc, sim/uhdm-integration-yosys/meta.yaml
This PR makes all metapackages always tied precisely to the packages built in the same CI workflow. This is required to make locking such metapackages possible and making sense.
However, there is a slight downside. Building a metapackage now will never succeed in cross-repository PRs. There's no Anaconda token in such workflows so the dependencies aren't uploaded after building and Conda won't be able to find them building the metapackage.
Building these recipes was tested locally. Jobs building metapackages are expected to fail in this PR if everything works well.
=> Correct metapackages

.github/workflows/build-packages.yml, pnr/odin_II/meta.yaml, pnr/symbiflow-vtr-gui/meta.yaml, pnr/symbiflow-vtr/meta.yaml, pnr/vtr-optimized/meta.yaml, pnr/vtr/meta.yaml
Related issue: #84
The `tbb-2021` and `tbb-devel-2021` available on `conda-forge` aren't
backward compatible. In fact, they will never be backward compatible
again: https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-threading-building-blocks-release-notes.html
The `tbb-2021` can't be used to run a package built with `tbb-2020`
because it even has a main library renamed from `libtbb.so.2` to
`libtbb.so.12`.
The new packages can't be currently built with TBBv2021 because CMake
isn't able to find it. It seems `include/tbb/tbb_stddef.h` is used
during the lookup but that file has been removed from `tbb-devel`
package. Also, currently `v2021` is only available from `conda-forge`.
=> Don't use incompatible v2021 `tbb` and `tbb-devel` packages

syn/symbiflow-yosys-plugins/fix_flags.patch, syn/symbiflow-yosys-plugins/meta.yaml
Flag setting introduced in https://github.com/SymbiFlow/yosys-symbiflow-plugins/commit/f02851af094f09d641972b7b3572014848e96615
results in the compiler flags not being set. That's because Conda's
compiler packages always set their own flags in the `conda-build`
working environment.
The patch simply reverses that commit.
=> symbiflow-yosys-plugins: Add patch restoring prev. flag setting in make

syn/yosys-uhdm/meta.yaml
Not only it solves build conflicts, which roots I'm unable to pinpoint,
but it's also more appropriate than the previous requirements
arrangement.
=> yosys-uhdm fix: Use some build requirements as the host ones instead

.github/workflows/build-packages.yml
GitHub Actions virtual environments doesn't have gcc-8 preinstalled
anymore: https://github.com/actions/virtual-environments/issues/2950
=> slang: verible: Use gcc-9

.github/workflows/build-packages.yml, pnr/nextpnr/fpga_interchange/build.sh, pnr/nextpnr/fpga_interchange/meta.yaml
The installed devices do miss patches information, relevant for constraints and LUTs definition.
This PR installs the correct devices and also removes the symbiflow-yosys run dependency package which should not be needed.
=> Fix nextpnr interchange installed device

pnr/arachne/meta.yaml
This sets the compiler version to be old enough not to complain about
some missing optimisation capabilities. Arachne isn't actively developed
anyway.
=> Fix Arachne compilation failed by newest gcc

.github/workflows/build-packages.yml, pnr/nextpnr/generic/meta.yaml, pnr/nextpnr/ice40/meta.yaml
macOS issues are fully fixed by raising compiler restriction that was once required to build these packages.
After solving one problem on Windows another came up so the specific issue was created for it: https://github.com/hdl/conda-eda/issues/120 .
=> nextpnr: Fix macOS issues and partly Windows

syn/yosys/XILINX_BRAM36.patch, syn/yosys/meta.yaml
This fixes yosys BRAM36 address to be complaint with UG473 
Signed-off-by: Maciej Dudek <mdudek@antmicro.com>
=> Add Xilinx BRAM36 patch

pnr/symbiflow-vtr-gui/meta.yaml
Tool's build scripts haven't been adapted to the latest GCC yet.
Co-authored by: Maciej Dudek <mdudek@antmicro.com>
=> symbiflow-vtr-gui: Stick to GCC <11

pnr/odin_II/meta.yaml, pnr/symbiflow-vtr-gui/meta.yaml
This commit fixes incompatibility of libxml2 with used compiler
=> symbiflow-vtr-gui; odin_ii: pin libxml2 version

syn/yosys-uhdm/meta.yaml
This PR fixes: ``libffi.so.7: cannot open shared object file: No such file or directory``: https://github.com/chipsalliance/sv-tests/issues/1758
=> yosys-uhdm: fix missing libffi in host

syn/symbiflow-yosys-plugins/build.sh, syn/symbiflow-yosys-plugins/fix_flags.patch, syn/symbiflow-yosys-plugins/meta.yaml, syn/yosys-plugins-symbiflow/build.sh, syn/yosys-plugins-symbiflow/fix_flags.patch, syn/yosys-plugins-symbiflow/meta.yaml, syn/yosys-uhdm/uhdm-plugin.patch, syn/yosys-uhdm/yosys.patch
Development of the uhdm-plugin was moved to symbiflow-yosys-plugins repository.
Now Surelog is required to build symbiflow-yosys-plugins. This PR adapts for this change.
=> Fix building uhdm plugin

.github/workflows/build-packages.yml, .gitmodules, xilinx/vivado/gen_metapackages.sh
The `aj-fix-ci` branch used in the workflow has been approved to be merged in: https://github.com/hdl/conda-ci/pull/20
Some adjustments have to be made, especially to the `xilinx-vivado` and `master-package` jobs but with these changes, the `scripts` submodule (pointing to `conda-ci`) can be removed.
The only place influencing script versions will now be held in the workflow and we won't need to bump submodules with each `conda-ci` change.
=> Fix paths in `conda-ci` and remove `scripts` submodule

.github/workflows/build-packages.yml, misc/open_pdks/build.sh, misc/open_pdks/condarc, misc/open_pdks/meta.yaml
Fixes #160
Depends on #161 
- package  as `open_pdks.sky130a`
- mimic `make timing` in build script to leverage conda environment for build dependencies
@mithro and @PiotrZierhoffer for review
@olofk @RTimothyEdwards  should we expose more combination of libs as different subpackages?
=> misc: add open_pdks

sim/icarus/meta.yaml
It's been fixed to the revision which last worked at the time but from my local test it seems the problem is gone with the current `master` branch.
=> sim/icarus: Follow the `master` branch again

misc/netgen/meta.yaml
/cc @mithro @RTimothyEdwards fyi
Looks like upstream has all of the fork's patch now:
https://github.com/RTimothyEdwards/netgen/commit/7e42483986631ec36a0e798f6ad1ef0145837ff0
https://github.com/RTimothyEdwards/netgen/commit/97b0d08e4fedd96fc4c2fd2c851fa1e7e0e907dd
=> misc/netgen: switch source to upstream

misc/open_pdks/meta.yaml
This should ensure that if installed in the same envirnment, magic has
the same version as the one used to build open_pdks.
=> misc/open_pdks: add magic as optional deps

.github/workflows/build-packages.yml, pnr/openroad/build.sh, pnr/openroad/condarc, pnr/openroad/gui-find-qt-only-if-enabled.patch, pnr/openroad/meta.yaml, pnr/openroad/odb-drt-disable-tests.patch, pnr/openroad/sta-add-install-options.patch
Fixes #150 
- distribute `openroad.app` `openroad.sta` and openroad.libsta` as subpackages
- distribute `openroad` meta package with `.app` and `.sta`
- patch to remove testing (failed to link against `rt`)
- user conda-eda convention (build from git/master, use `conda-build-prepare` for version string)
@PiotrZierhoffer @mithro for review
@maliberty fyi
=> pnr: add openroad

.github/workflows/build-packages.yml, hls/xls/add-dist-rule.patch, hls/xls/build.sh, hls/xls/condarc, hls/xls/meta.yaml, hls/xls/skip-python-requirements.patch, hls/xls/use-llvm-toolchain.patch
Fixes #169
- package the following binaries:
- `interpreter_main`
- `ir_converter_main`
- `opt_main`
- `codegen_main`
- drop python bazel deps in favor of conda
=> hls: add xls

misc/magic/add-commit-flag.patch, misc/magic/meta.yaml
That'll help generating a valid SOURCES file for the open_pdks package in the format that OpenLane is expecting:
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docker/open_pdks/Dockerfile#L87
/cc @RTimothyEdwards let me know if you'd like this patch upstream.
=> misc/magic: add commit flag

sim/icarus/build.sh, sim/icarus/meta.yaml
This is for testing that YAML multiline block syntax can be used to avoid "too long" summary lines. Since git makes version control per line, it is not desirable to have full paragraphs written without newlines.
BTW, some tests which are duplicated in the build script and the test script are removed from the former.
=> sim/icarus: use multiline block syntax for the summary string

syn/yosys-uhdm/build.sh
``yosys-uhdm`` package is still used by ``fpga-tool-perf``. I'm working on removing it and start using ``symbiflow-yosys-plugins`` directly: https://github.com/chipsalliance/fpga-tool-perf/pull/413. After that, ``yosys-uhdm`` can be removed completly.
Until then, lets fix failing CI.
=> yosys-uhdm: Remove yosys-patches

misc/open_pdks/meta.yaml
This reverts commit 3549634c1895f6666906c361018517a20dc6bca5 as
https://github.com/RTimothyEdwards/magic/issues/162 is fixed upstream.
=> Revert "misc/open_pdks: Constrain magic version"

sim/verilator/meta.yaml
These changes should fix the Verilator's "Could not find compiler" issue: https://github.com/google/CFU-Playground/issues/568
For no good reason Conda installs a very old compiler package with Verilator even though there are no conflicts with the latest one: https://github.com/google/CFU-Playground/issues/568#issuecomment-1178890026
The old compiler packages (prior to v8) used a different prefix for the executables hence the problem.
Let's prevent Conda from installing Verilator with such compiler packages.
=> sim/verilator: linux: Require compiler package v8 or newer

misc/tree-sitter-verilog/build.sh, misc/tree-sitter-verilog/meta.yaml
For as long as I can check in the CI logs there have been troubles with
installing the latest `tree_sitter` package from PyPI (v0.20 currently):
```
No matching distribution found for setuptools>=43.0.0
```
The job still worked because Pip was then checking whether older
packages work and installed the old `tree_sitter` v0.2.1 package.
The latest Pip v22.1.2 exits with failure instead which made the job
fail for a week or so.
By using `py-tree-sitter` directly always the latest version will be
used and the PyPI dependency is removed completely.
=> misc/tree-sitter-verilog: Use `py-tree-sitter` directly

ci/conda-get.sh
Installing python without updating conda beforehand caused an error `OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /tmp/really-long-path/conda/lib/python3.9/site-packages/certifi/cacert.pem` in github actions. Updating conda before the installation fixed this issue.
=> update conda before installing packages

bit/prjtrellis/build.sh, pnr/nextpnr/ecp5/build.sh, pnr/nextpnr/fpga_interchange/build.sh, pnr/nextpnr/generic/build.sh, pnr/nextpnr/ice40/build.sh, pnr/nextpnr/nexus/build.sh, pnr/nextpnr/xilinx/build.sh
By default, CMake looks for the latest possible version of Python in the projects where CMake minimum version is less than 3.15.
Since 3.15 there's a new policy making it use the first Python found within the given version constraints.
The `nextpnr` and `prjtrellis` CMakeLists.txt allow CMake to be older than 3.15 which is why the old policy is used.
Forcing CMake to use a new policy fixes the nextpnr and prjtrellis problems with finding Python development headers on Linux.
After such a change CMake uses Conda Python which provides the headers instead of the host Python for which the headers aren't available.
There are some additional minor changes which are described in the commit messages.
=> nextpnr/prjtrellis: Fix CMake find strategy for Python

pnr/nextpnr/generic/build.sh, pnr/nextpnr/ice40/build.sh
The change is only made to the recipes which are actually built for macOS.
=> pnr/nextpnr: Disable symbol availability check on macOS

.github/workflows/Build.yml, misc/openlane/1439.patch, misc/openlane/build.sh, misc/openlane/disable-missing-tools.tcl, misc/openlane/env.tcl, misc/openlane/meta.yaml
Fixes #244
/cc @QuantamHD @mithro
=> misc: add openlane

ci/conda-get.sh
Looks like miniconda started using bashism:
```
./Miniconda3-latest-Linux-x86_64.sh: 444: [[: not found
```
See https://github.com/google/CFU-Playground/issues/752
=> ci/conda-get: use bash to run miniconda

.github/workflows/Build.yml, misc/klayout/build.sh, misc/klayout/force-python-dynamic-link.patch, misc/klayout/meta.yaml
Based on @klayoutmatthias's [fork](https://github.com/klayoutmatthias/staged-recipes/tree/klayout/recipes/klayout) of https://github.com/conda-forge/staged-recipes/pull/20396.
Wanted to just build the CLI to aligned with #250 and #193 but couldn't find a build option to disable QT while still keeping `klayout_main`.
Fixes #175
=> misc: add klayout

pnr/vtr-optimized/build.sh, pnr/vtr-optimized/condarc, pnr/vtr-optimized/meta.yaml, pnr/vtr-optimized/vpr-cmake.patch
The goal of this PR is to fix failing builds of 'vtr-optimized-linux' package. Changes made:
* install latest tbb version instead of '<2021.0.0a0'
* install prjxray, prjxray-db, prjxray-tools, pyyaml
* add litex-hub channel to condarc (needed for prjxray-db, prjxray-tools)
* add vpr-cmake.patch for the vtr repo with the -fprofile-correction flag
=> Fix failing builds of vtr-optimized-linux

pnr/nextpnr/fpga_interchange/meta.yaml
The tbb library, besides being required during build time, is also required to be in a specific version when using the nextpnr-fpga-interchange package.
=> Add tbb to run dependencies for nextpnr-fpga-interchange

pnr/nextpnr/fpga_interchange/meta.yaml
Removed the requirement for TBB version for Nextpnr FPGA Interchange so that `nextpnr-fpga_interchange` won't conflict with `vtr-optimized`.
=> Unpin TBB dependency for Nextpnr FPGA Interchange

.github/workflows/Build.yml, sim/ngspice/build.sh, sim/ngspice/meta.yaml
This a simpler version than https://github.com/conda-forge/ngspice-feedstock maintained @stuarteberg with minimal dependencies and no gui (see #193 and #250 for rational).
This will allow us to build an installer for the sky130/gf180 analog flow (per #245).
Fixes #49.
=> sim: add ngspice

.github/workflows/Build.yml, bit/prjoxide/build.sh, bit/prjoxide/meta.yaml, ci/common.sh, misc/tree-sitter-verilog/meta.yaml, misc/xschem/meta.yaml, sim/ngspice/meta.yaml, sim/verilator-uhdm/meta.yaml, sim/verilator/meta.yaml, sv-front/surelog/meta.yaml, sv-front/sv-parser/meta.yaml, syn/yosys-uhdm/build.sh, syn/yosys-uhdm/uhdm-plugin.patch, syn/yosys/makefile-conda-config.patch
This PR migrates package builds for Linux to GHA custom runners.
The runners have less software installed by default, which resulted in the need make changes in some build scripts and requirements lists.
=> Use custom runners

sim/verilator/run_test.sh
Verilator is run without proper installation, therefore it cannot find the std library.
=> Update Verilator tests

misc/open_pdks/meta.yaml
https://github.com/hdl/conda-eda/commit/a852977eea1fd6b3879eb7cab9567983c074e4ac changed meta.yaml to use `git_url` causing conda to fetch gitsubmodules recursively.
Reverting back to tarball allow us to make sure we only clone each dependencies once.
=> misc/open_pdks: fix source handling

.github/workflows/Build.yml, misc/netgen/build.sh, misc/netgen/meta.yaml, misc/netgen/remove-x11-requirement.patch
Just disable X11, since Conda doesn't include the requisite packages.
=> Build netgen on macos

misc/openlane/build.sh, misc/openlane/meta.yaml
openlane is tcl scripts, so there is no reason for it to be arch-specific.
=> misc/openlane: set openlane to be noarch

.github/workflows/Build.yml, misc/klayout/build.sh, misc/klayout/meta.yaml
This fixes the klayout package so that it now builds properly on `osx-arm64`.
=> Fix klayout build on macos

docs/shields.inc
This PR updates the syntax of the broken shield/badge in the readme. See https://github.com/badges/shields/issues/8671.
=> readme: update shield syntax (badges/shields#8671)

docs/conf.py
Building the docs is failing because Sphinx 6.0 requires extlink strings to contain exactly one '%s'. This PR fixes it.
=> docs/conf: update extlinks syntax

ci/conda-get.sh, ci/install.sh
This is a lame attempt at fixing #324.
/cc @xobs @PiotrZierhoffer @ajelinski
=> ci: do not force python3.7

hls/xls/bump-python-deps.patch, hls/xls/meta.yaml, hls/xls/test_stdlib.x
Should fix recent XLS build failure:
https://github.com/hdl/conda-eda/actions/runs/5127108900/jobs/9222395220
- use "compatible release" version selector, see https://peps.python.org/pep-0440/#compatible-release
- update stdlib tests to new DSLX syntax
Fixes #331
=> hls/xls: bump python deps

misc/open_pdks/sky130a/meta.yaml
Fixes #329 
Also filed https://github.com/google/skywater-pdk/issues/422 to fix it properly upstream.
=> misc/open_pdks/sky130a: use same python version as CI

.github/workflows/Build.yml, misc/klayout/meta.yaml, misc/netgen/meta.yaml, misc/open_pdks/gf180mcuc/meta.yaml, misc/open_pdks/sky130a/423.patch, misc/open_pdks/sky130a/meta.yaml, misc/openlane/meta.yaml, pnr/openroad/meta.yaml
- github/workflow: add py310 entries
- openroad: use PYTHON_VERSION
- klayout: use pin_compatible
- openlane: update test design
- misc/open_pdks: move python to build dep
- misc/netgen: remove python dep
Related #343 #72
=> build packages for python 3.10

.github/workflows/Build.yml, misc/openlane/meta.yaml
- github/workflows: add open_pdks jobs dependencies (required by tests)
- misc/openlane: add gf180mcuC test
- misc/openlane: set python version from ci
- remove ubuntu 22.04 requirements (as python comes from the conda install)
Hopefully fixes #343
=> misc/openlane: improve pdk testing

pnr/openroad/disable-cluster-flops-cmd.patch, pnr/openroad/meta.yaml, pnr/openroad/remove-boost-span-deps.patch
refreshed the boost patch again: https://github.com/proppy/conda-eda/blob/437ca9a3fc534c82f822f3e552857453086215c0/pnr/openroad/remove-boost-span-deps.patch
@QuantamHD do you think it would be worth landing something cleaner upstream? e.g: make the dependency on boost-span optional (since it's only used in tests)
=> pnr/openroad: fix patch

pnr/openroad/disable-cluster-flops-cmd.patch, pnr/openroad/layouttabs-include-qtglobal.patch, pnr/openroad/meta.yaml, pnr/openroad/opendp-numeric.patch
Currently, the OpenROAD build fails, because this patch can't be applied.
I actually had to do some more changes in my fork to get the build working again, but I'm not sure how much of that is because of my runner. So maybe this will do.
Fix https://github.com/hdl/conda-eda/issues/368
=> OpenROAD: Fix package

pnr/openroad/meta.yaml
Currently  `git describe` is failing within the OpenROAD build which leads to the version number compiled into the binary falling back to a hash which doesn't work well for version checking.
https://github.com/hdl/conda-eda/actions/runs/8012258777/job/21887187187#step:5:2091
```
23:23:44 | CMake Warning at CMakeLists.txt:98 (message):
23:23:44 |   OpenROAD git describe failed, using sha1 instead
```
The reson seems to be that cmake is called with `-DCMAKE_FIND_ROOT_PATH` such that `find_package(Git)` fails. Easiest solution seems to be to just add git to the build requirements, which this patch does. Alternatively we could probably pass `GIT_EXECUTABLE` to cmake.
Fix https://github.com/hdl/conda-eda/issues/365
=> OpenROAD: Fix version string in binary
