hdl/conda-eda

- .travis.yml
- misc/magic/build.sh
- misc/magic/condarc
- misc/magic/csh.patch
- misc/magic/ld.patch
- misc/magic/meta.yaml
> Add magic package

- .travis.yml
This started to fail regularily, causing problems with other PRs
> Allow Icarus to fail on Windows

- .travis.yml
This is a follow-up to #31.
Travis does not allow access to secret variables if the PR comes from another repo. This is a problem I don't know how to handle in a super robust way at the moment, but I think it's ok for now.
> Stages rework

- misc/magic/meta.yaml
Signed-off-by: Grzegorz Latosinski <glatosinski@antmicro.com>
> misc: magic: allowed Python version to be >= 3.7

- .github/workflows/build-packages.yml
Updating repo references, sumbodules etc
> Hdl migration

- syn/antmicro-yosys-plugins/antmicro-yosys.patch
> Fix antmicro-yosys-plugins

- syn/yosys/meta.yaml
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
> syn: yosys: update repository URL

- .github/workflows/build-packages.yml
- pnr/nextpnr/fpga_interchange/build.sh
- pnr/nextpnr/fpga_interchange/capnp_add_prefix_include_dir.patch
- pnr/nextpnr/fpga_interchange/change_patch_format.patch
- pnr/nextpnr/fpga_interchange/condarc
- pnr/nextpnr/fpga_interchange/meta.yaml
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
> nextpnr: add fpga-interchange target

- pnr/vtr-optimized/build.sh
- pnr/vtr-optimized/condarc
- pnr/vtr-optimized/meta.yaml
Fixes the vtr-optimized package build
> vtr-optimized: remove conda-forge

- .github/workflows/build-packages.yml
- syn/yosys-plugins-symbiflow/build.sh
- syn/yosys-plugins-symbiflow/fix_flags.patch
- syn/yosys-plugins-symbiflow/meta.yaml
Adds package with symbiflow-plugins for yosys.
There is package very similar to this one, but that one uses sybmiflow-yosys and not main stream one.
> Yosys plugins symbiflow

- .github/workflows/build-packages.yml
- pnr/nextpnr/nexus/build.sh
- pnr/nextpnr/nexus/meta.yaml
PR adds nextpnr-nexus to Place and Route.
> pnr: Add nextpnr-nexus

- .github/workflows/build-packages.yml
- syn/symbiflow-yosys-plugins/meta.yaml
> syn: yosys-plugins: depend on yosys and not symbiflow-yosys

- .github/workflows/build-packages.yml
- misc/gperftools/build.sh
- misc/gperftools/meta.yaml
- misc/libunwind/build.sh
- misc/libunwind/meta.yaml
- sv-front/surelog-uhdm/condarc
- sv-front/surelog/condarc
- syn/yosys-uhdm/build.sh
- syn/yosys-uhdm/condarc
- syn/yosys-uhdm/meta.yaml
- syn/yosys-uhdm/uhdm-plugin.patch
- syn/yosys-uhdm/yosys.patch
This PR replaces building uhdm as a part of yosys frontend to external plugin.
> yosys-uhdm: use uhdm-plugin; add gperftools and libunwind packages

- .github/workflows/build-packages.yml
- sim/verilator-uhdm/build.sh
- sim/verilator-uhdm/condarc
- sim/verilator-uhdm/meta.yaml
> verilator-uhdm: remove condarc channel

- syn/yosys-uhdm/uhdm-plugin.patch
- syn/yosys-uhdm/yosys.patch
> yosys-uhdm: update yosys patches

- syn/symbiflow-yosys-plugins/fix_flags.patch
- syn/yosys-plugins-symbiflow/fix_flags.patch
This PR updates yosys-plugins-symbiflow patch to match changes in current master revision.
> yosys-plugins-symbiflow; symbiflow-yosys-plugins: update patch

- .github/workflows/build-packages.yml
- .github/workflows/tuttest.yml
This is to verify prjoxide build
> Update jobs missed to use Ubuntu 20.04

- bit/prjxray-db/build.sh
> bit: prjxray-db: add spartan7

- misc/netgen/condarc
- misc/netgen/meta.yaml
- remove conda-forge deps (tcsh)
- use cdt for x11 libs
Related to #193
> misc/netgen: remove conda-forge deps

- .github/workflows/build-packages.yml
- misc/open_pdks/build.sh
- misc/open_pdks/condarc
- misc/open_pdks/meta.yaml
- fetch conda-forge deps wheel from pipy
- install transitive deps from main
Related to #193
> misc/open_pdks: remove conda-forge deps

- pnr/openroad/odb-drt-disable-tests.patch
/cc @ajelinski @PiotrZierhoffer
> pnr/openroad: update patches

- hls/xls/build.sh
- hls/xls/meta.yaml
- hls/xls/test_stdlib.x
> hls/xls: add stdlib

- .github/workflows/Build.yml
- misc/open_pdks/build.sh
- misc/open_pdks/meta.yaml
- misc/xschem/build.sh
- misc/xschem/meta.yaml
> misc: add xschem

- misc/klayout/build.sh
> misc/klayout: fix plugins location

- pnr/openroad/build.sh
- pnr/openroad/disable-mpl2-and-par.patch
- pnr/openroad/meta.yaml
Build openroad for osx.
This has been tested on an arm64 build, but has not yet been tested on x86_64.
Note that this does an absolutely awful thing in patching the cmake qt files, but it seems to work.
> Build GUI for openroad on osx

- .github/workflows/Build.yml
- misc/magic/build.sh
- misc/magic/meta.yaml
- misc/magic/rename-region-to-netregion.patch
Fix magic so that it can build on osx, albeit without X11.
This requires a patch, and is waiting on https://github.com/RTimothyEdwards/magic/pull/222, at which point we can remove the patch.
> Build magic on osx

- .github/workflows/Build.yml
- misc/tcllib/meta.yaml
- backported from https://github.com/conda-forge/tcllib-feedstock/
- needed by openlane
> misc: add tcllib

- misc/open_pdks/gf180mcuc/meta.yaml
- misc/open_pdks/gf180mcuc/use-sources-from-conda.patch
> misc/open_pdks.gf180mcu: add pv repo

- hls/xls/build.sh
> hls/xls: fix ir_convert rules

- pnr/openroad/find-tcl-library.patch
- pnr/openroad/meta.yaml
- pnr/openroad/remove-boost-span-deps.patch
- refresh patches
- use the same python version as the CI
Fixes #332 
/cc @QuantamHD @xobs
> pnr/openroad: fix build

- misc/open_pdks/gf180mcuc/fix-klayout-lvs-path.patch
- misc/open_pdks/gf180mcuc/meta.yaml
> misc/open_pdks/gf180mcuc: fix klayout lvs path

- hls/xls/test_stdlib.x
Fixes #339 
/cc @cdleary @QuantamHD
> hls/xls/test: remove wildcards

- hls/xls/bump-python-deps.patch
> hls/xls: refresh patches

- misc/openlane/meta.yaml
> misc/openlane: add verilator dep

- .github/workflows/Build.yml
- hls/xls/test_stdlib.x
- update base image
- update system deps
- fix tests
Fixes #367 (hopefully)
> hls/xls: fix package

- misc/klayout/meta.yaml
> misc/klayout: add missing libgit2 dep
